version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo-list
    volumes:
        - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432